# Site settings
author: OMEGA MARKOS
title: king county housing price EDA
header-img: img/home-bg.png
email: omegaghirmay@gmail.com
copyright_name: OMEGA MARKOS
description: > # this means to ignore newlines until "baseurl:"
  Explanatory Data Analysis
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  omegamarkos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
